version: "3.2"
  services:
    mysql:
          image: "mysql"
          ports:
                - "3001:8005"
          environment:
                      - MYSQL_ROOT_PASSWORD=
                      - MYSQL_USER=
                      - MYSQL_PASSWORD= 
                      - MYSQL_DATABASE=
    backend:
              build: <nome do arq no ubuntu>
              ports:
                    - "3000:3000"
              depends_on:
                         - mysql
                         - ngrok
              volumes:
                      - /<nome do arq no ubuntu>/src/app
              container_name: 
                              - <nome da pasta criada no ubuntu>
    